# Generated by Django 2.0.13 on 2019-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='variedad',
            field=models.CharField(default=400, max_length=100),
            preserve_default=False,
        ),
    ]
