# Generated by Django 2.0.13 on 2019-04-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_variedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='variedad',
            new_name='tipo',
        ),
    ]
