# Generated by Django 2.0.13 on 2019-04-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_factura_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
