# Generated by Django 2.0.13 on 2019-04-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190411_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
    ]
